In [1]:
import numpy as np

In [3]:
np.load("d_vect_lowbad.npy", allow_pickle=True)

array({'/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/11cut.wav': array([ 2.5480927e-04, -3.8767580e-03, -6.0841918e-05, ...,
        6.5687736e-03,  7.0051092e-04,  4.7959657e-05], dtype=float32), '/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/21cut.wav': array([ 1.75236215e-04, -3.58073763e-03, -1.01901394e-04, ...,
        2.94496175e-02, -4.52890201e-03, -7.42394332e-05], dtype=float32), '/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/14cut.wav': array([ 0.00026363, -0.0046466 , -0.0001026 , ...,  0.02340977,
       -0.00297121, -0.00023441], dtype=float32), '/home/hanqing/1ASpeakerRecognition/16kHzUltradata/16/bad/22cut.wav': array([ 4.2174084e-04,  2.2890102e-02, -1.0161706e-05, ...,
        2.9194003e-02, -1.7074841e-03,  6.0035457e-04], dtype=float32), '/home/hanqing/1ASpeakerRecognition/16kHzUltradata/16/bad/13cut.wav': array([ 2.2946470e-04,  1.4204568e-02, -9.3159848e-05, ...,
        2.8074848e-02,  9.1070787e-04,  3.6398106e-04], dtype=float

In [4]:
speaker_embeddings = np.load("d_vect_lowbad.npy", allow_pickle=True)

In [36]:
for k, v in speaker_embeddings.item().items():
    print (k,v)

/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/11cut.wav [ 2.5480927e-04 -3.8767580e-03 -6.0841918e-05 ...  6.5687736e-03
  7.0051092e-04  4.7959657e-05]
/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/21cut.wav [ 1.75236215e-04 -3.58073763e-03 -1.01901394e-04 ...  2.94496175e-02
 -4.52890201e-03 -7.42394332e-05]
/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/14cut.wav [ 0.00026363 -0.0046466  -0.0001026  ...  0.02340977 -0.00297121
 -0.00023441]
/home/hanqing/1ASpeakerRecognition/16kHzUltradata/16/bad/22cut.wav [ 4.2174084e-04  2.2890102e-02 -1.0161706e-05 ...  2.9194003e-02
 -1.7074841e-03  6.0035457e-04]
/home/hanqing/1ASpeakerRecognition/16kHzUltradata/16/bad/13cut.wav [ 2.2946470e-04  1.4204568e-02 -9.3159848e-05 ...  2.8074848e-02
  9.1070787e-04  3.6398106e-04]
/home/hanqing/1ASpeakerRecognition/16kHzUltradata/16/bad/25cut.wav [ 3.7865329e-04  2.0439619e-02 -1.2669695e-05 ...  3.9950345e-02
 -2.4521835e-03  5.4839579e-04]
/home/hanqing/1ASpeakerRecog

In [6]:
speaker_embeddings.item()['/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/11cut.wav']

array([ 2.5480927e-04, -3.8767580e-03, -6.0841918e-05, ...,
        6.5687736e-03,  7.0051092e-04,  4.7959657e-05], dtype=float32)

In [37]:
len(speaker_embeddings.item())

12

In [14]:
speaker14_1 = speaker_embeddings.item()['/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/11cut.wav']

In [15]:
speaker14_2 = speaker_embeddings.item()['/home/hanqing/1ASpeakerRecognition/16kHzUltradata/14/bad/21cut.wav']

In [16]:
speaker16_1 = speaker_embeddings.item()['/home/hanqing/1ASpeakerRecognition/16kHzUltradata/16/bad/22cut.wav']

In [17]:
speaker16_2 = speaker_embeddings.item()['/home/hanqing/1ASpeakerRecognition/16kHzUltradata/16/bad/13cut.wav']

In [24]:
speaker14_1 = speaker14_1.reshape(1,-1)

In [25]:
speaker14_2 = speaker14_2.reshape(1,-1)

In [28]:
speaker16_1 = speaker16_1.reshape(1,-1)

In [29]:
speaker16_2 = speaker16_2.reshape(1,-1)

In [8]:
len(speaker14)

2048

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
cosine_similarity(speaker14_1, speaker14_1, dense_output=True)

array([[1.]], dtype=float32)

In [27]:
cosine_similarity(speaker14_1, speaker14_2, dense_output=True)

array([[0.87954473]], dtype=float32)

In [30]:
cosine_similarity(speaker14_1, speaker16_2, dense_output=True)

array([[0.7875314]], dtype=float32)

In [31]:
cosine_similarity(speaker16_1, speaker16_2, dense_output=True)

array([[0.9527666]], dtype=float32)

In [32]:
cosine_similarity(speaker14_1, speaker16_1, dense_output=True)

array([[0.7542808]], dtype=float32)

In [33]:
cosine_similarity(speaker14_2, speaker16_1, dense_output=True)

array([[0.7634639]], dtype=float32)

In [34]:
cosine_similarity(speaker14_1, speaker16_2, dense_output=True)

array([[0.7875314]], dtype=float32)